# todo: Ansible does not allow us to pass a cleartext password through the user module 
# ? use this command in node server: ansible-playbook changepass.yml --extra-vars newpassword=abc123


---
- name: 'Add or update user password'
  hosts: all

  tasks:
  - name: 'Change "george" password'
    user:  # ? this module is used to change the users settings
      name: george
      update_password: always
      password: " {{ newpassword|password_hash('sha512') }} "  # ! the first 'newpassword' is a variable, it can be any other name. The second one 'password_hash('sha512') is the encryption used 
      