# Sometimes you want a task to run only when a change is made on a machine. 
# For example, you may want to restart a service if a task updates the configuration of that service, but not if the configuration is unchanged. 
# Ansible uses handlers to address this use case. Handlers are tasks that only run when notified.

---
- name: Verify apache installation
  hosts: localhost
  tasks:
  - name: Ensure apache is at latest version
    yum: 
      name: httpd
      state: latest  # this check if the package is at the lastest version

  - name: Copy updated apache config file
    copy: 
      src: /etc/httpd/conf/httpd.conf
      dest: /tmp/httpd.conf
    notify:
    - Restart apache  # ? This will call the handler located at the end of the playbook.

  - name: Ensure apache is running 
    service: 
      name: httpd
      state: started

  handlers:  # ? this is called by the "- Restart apache" above.
    - name: Restart apache
      service: 
        name: httpd
        state: restarted
