
# this is how you invoke the playbook from the tag.
# ? ansible-playbook httpByTags.yml -t i-httpd

# show you all the tags in the playbook.
# ? ansible-playbook httpByTags.yml --list-tags

#  with this you can skip a certain tag.
# ? ansible-playbook httpByTags.yml --skip-tags i-httpd,

---
- name: Setup Apache server
  hosts: localhost
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags: i-httpd  # ? this is the name of the tag

  - name: Start httpd
    service:
      name: httpd
      state: started
    tags: s-httpd  # ? this is the name of the tag