
# ? ansible-playbook httpByTags.yml -t i-httpd, this is how you invoke the playbook from the tag.
# ? ansible-playbook httpByTags.yml --list-tags, show you all the tags in the playbook.

---
- name: Setup Apache server
  hosts: localhost
  tasks:
  - name: Install httpd
    yum:
      name: httpd
      state: present
    tags: i-httpd  # ? this is the name of the tag

  - name: Start httpd
    service:
      name: httpd
      state: started
    tags: s-httpd  # ? this is the name of the tag