---
- name: Copy file to remote clients
  hosts: all
  vars:
    srcfile: /home/angel/someFile
  tasks:

  - name: Copying file
    become: true
    copy:
      src: "{{ srcfile }}"
      dest: /tmp
      owner: angel
      group: angel
      mode: 0644